name: bump-version
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version to bump
        required: true
        options:
          - patch
          - minor
          - major
jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Downloading bump version script
        run: |
          curl -L ${{ vars.BUMP_VERSION_URL }} -o bump-version.sh
          chmod +x bump-version.sh
      - name: Setting git config
        run: |
          git config user.email "development+github@freedom.tm"
          git config user.name "Freedom CI/CD"
      - name: Bumping version
        run: ./bump-version.sh ${{ inputs.version }}
